import HexGramSchmidt
import HexMatrix

/-!
Core LLL predicates and integer state scaffolding for `hex-lll`.

This module introduces the executable lattice-membership and independence
predicates used by the LLL library together with the `δ`-reducedness contract
and the all-integer `LLLState` record consumed by later algorithmic phases.
-/

namespace Hex

namespace Matrix

/-- `v` lies in the integer lattice generated by the rows of `b`. -/
def memLattice (b : Matrix Int n m) (v : Vector Int m) : Prop :=
  ∃ c : Vector Int n, rowCombination b c = v

/-- The rows of `b` are linearly independent, witnessed by positivity of each
leading principal Gram determinant. -/
def independent (b : Matrix Int n m) : Prop :=
  ∀ k : Fin n, 0 < det (submatrix (gramMatrix b) k)

end Matrix

namespace LLLCore

/-- Recover the squared norm of a Gram-Schmidt basis vector. -/
private def basisNormSq (basis : Matrix Rat n m) (i : Fin n) : Rat :=
  Vector.normSq (basis.row i)

end LLLCore

/-- A basis is `δ`-LLL-reduced when it is size-reduced and satisfies the
Lovasz condition at every adjacent pair. -/
def isLLLReduced (b : Matrix Int n m) (δ : Rat) : Prop :=
  let basis := GramSchmidt.Int.basis b
  let coeffs := GramSchmidt.Int.coeffs b
  (∀ i j, (hi : i < n) → (hji : j < i) →
      let iFin : Fin n := ⟨i, hi⟩
      let jFin : Fin n := ⟨j, Nat.lt_trans hji hi⟩
      let μ := coeffs[iFin][jFin]
      4 * μ * μ ≤ 1) ∧
    ∀ i, (hi : i + 1 < n) →
      let iFin : Fin n := ⟨i, Nat.lt_trans (Nat.lt_succ_self i) hi⟩
      let ip1Fin : Fin n := ⟨i + 1, hi⟩
      let μ := coeffs[ip1Fin][iFin]
      δ * LLLCore.basisNormSq basis iFin ≤
        LLLCore.basisNormSq basis ip1Fin + μ * μ * LLLCore.basisNormSq basis iFin

/-- Integer-only state for later LLL reduction steps. The proof-facing fields
connect the stored Gram determinants and scaled coefficients to the
noncomputable Gram-Schmidt projections of `b`. -/
structure LLLState (n m : Nat) where
  b : Matrix Int n m
  ν : Matrix Int n n
  d : Vector Nat (n + 1)
  ν_eq : ∀ i j, (hi : i < n) → (hj : j < n) → j < i →
      ((ν.get ⟨i, hi⟩).get ⟨j, hj⟩ : Rat) =
        (d.get ⟨j + 1, Nat.succ_lt_succ hj⟩ : Rat) *
          ((GramSchmidt.Int.coeffs b).get ⟨i, hi⟩).get ⟨j, hj⟩
  d_eq : ∀ i, (hi : i < n + 1) →
      d.get ⟨i, hi⟩ = GramSchmidt.Int.gramDet b i (Nat.le_of_lt_succ hi)

namespace LLLState

/-- Recover a single rational Gram-Schmidt coefficient from the integer state.
This exists for the proof layer; later executable code continues to work over
the stored integer data. -/
noncomputable def gramSchmidtCoeff (s : LLLState n m) (i j : Nat)
    (hi : i < n) (hj : j < n) : Rat :=
  (((s.ν.get ⟨i, hi⟩).get ⟨j, hj⟩ : Int) : Rat) / (s.d.get ⟨j + 1, Nat.succ_lt_succ hj⟩ : Rat)

/-- The multiplicative potential used by the LLL termination argument:
`d₁ * ... * dₙ`. -/
def potential (s : LLLState n m) : Nat :=
  (List.finRange n).foldl
    (fun acc i => acc * s.d.get ⟨i.val + 1, Nat.succ_lt_succ i.isLt⟩)
    1

end LLLState

end Hex
