import HexGramSchmidt
import HexMatrix

/-!
Core LLL predicates and integer state for `hex-lll`.

This module introduces the executable lattice-membership and independence
predicates used by the LLL library together with the `δ`-reducedness contract,
the Gram-Schmidt norm identities stated over those predicates, and the
all-integer `LLLState` record consumed by later algorithmic phases.
-/

namespace Hex

namespace Matrix

/-- `v` lies in the integer lattice generated by the rows of `b`. -/
def memLattice (b : Matrix Int n m) (v : Vector Int m) : Prop :=
  ∃ c : Vector Int n, rowCombination b c = v

/-- The rows of `b` are linearly independent, witnessed by positivity of each
leading principal Gram determinant. -/
def independent (b : Matrix Int n m) : Prop :=
  ∀ k : Fin n, 0 < det (submatrix (gramMatrix b) k)

/-- Product of the squared Gram-Schmidt basis norms along the first `k` rows. -/
noncomputable def gramSchmidtNormProduct (b : Matrix Int n m) (k : Nat) (hk : k ≤ n) : Rat :=
  (List.finRange k).foldl
    (fun acc j =>
      let jn : Fin n := ⟨j.val, Nat.lt_of_lt_of_le j.isLt hk⟩
      acc * Vector.normSq ((GramSchmidt.Int.basis b).row jn))
    1

theorem gramDet_eq_prod_normSq (b : Matrix Int n m)
    (hli : b.independent) (k : Nat) (hk : k ≤ n) :
    (GramSchmidt.Int.gramDet b k hk : Rat) = gramSchmidtNormProduct b k hk := by
  sorry

theorem gramDet_pos (b : Matrix Int n m)
    (hli : b.independent) (k : Nat) (hk : k ≤ n) (hk' : 0 < k) :
    0 < GramSchmidt.Int.gramDet b k hk := by
  sorry

theorem basis_normSq (b : Matrix Int n m)
    (hli : b.independent) (k : Nat) (hk : k < n) :
    Vector.normSq ((GramSchmidt.Int.basis b).row ⟨k, hk⟩) =
      (GramSchmidt.Int.gramDet b (k + 1) (Nat.succ_le_of_lt hk) : Rat) /
        (GramSchmidt.Int.gramDet b k (Nat.le_of_lt hk) : Rat) := by
  sorry

theorem normSq_latticeVec_ge_min_basis_normSq
    (b : Matrix Int n m) (hli : b.independent)
    (v : Vector Int m) (hv : b.memLattice v) (hv' : v ≠ 0) :
    ∃ i : Fin n,
      Vector.normSq ((GramSchmidt.Int.basis b).row i) ≤ ((Vector.normSq v : Int) : Rat) := by
  sorry

end Matrix

namespace LLLCore

/-- Recover the squared norm of a Gram-Schmidt basis vector. -/
private def basisNormSq (basis : Matrix Rat n m) (i : Fin n) : Rat :=
  Vector.normSq (basis.row i)

end LLLCore

/-- A basis is `δ`-LLL-reduced when it is size-reduced and satisfies the
Lovasz condition at every adjacent pair. -/
def isLLLReduced (b : Matrix Int n m) (δ : Rat) : Prop :=
  let basis := GramSchmidt.Int.basis b
  let coeffs := GramSchmidt.Int.coeffs b
  (∀ i j, (hi : i < n) → (hji : j < i) →
      let iFin : Fin n := ⟨i, hi⟩
      let jFin : Fin n := ⟨j, Nat.lt_trans hji hi⟩
      let μ := coeffs[iFin][jFin]
      4 * μ * μ ≤ 1) ∧
    ∀ i, (hi : i + 1 < n) →
      let iFin : Fin n := ⟨i, Nat.lt_trans (Nat.lt_succ_self i) hi⟩
      let ip1Fin : Fin n := ⟨i + 1, hi⟩
      let μ := coeffs[ip1Fin][iFin]
      δ * LLLCore.basisNormSq basis iFin ≤
        LLLCore.basisNormSq basis ip1Fin + μ * μ * LLLCore.basisNormSq basis iFin

/-- Integer-only state for later LLL reduction steps. The proof-facing fields
connect the stored Gram determinants and scaled coefficients to the
noncomputable Gram-Schmidt projections of `b`. -/
structure LLLState (n m : Nat) where
  b : Matrix Int n m
  ν : Matrix Int n n
  d : Vector Nat (n + 1)
  ν_eq : ∀ i j, (hi : i < n) → (hj : j < n) → j < i →
      ((ν.get ⟨i, hi⟩).get ⟨j, hj⟩ : Rat) =
        (d.get ⟨j + 1, Nat.succ_lt_succ hj⟩ : Rat) *
          ((GramSchmidt.Int.coeffs b).get ⟨i, hi⟩).get ⟨j, hj⟩
  d_eq : ∀ i, (hi : i < n + 1) →
      d.get ⟨i, hi⟩ = GramSchmidt.Int.gramDet b i (Nat.le_of_lt_succ hi)

namespace LLLState

/-- Integer nearest-quotient used by the LLL size-reduction test. -/
private def nearestQuotient (νjk : Int) (dj1 : Nat) : Int :=
  Int.fdiv (2 * νjk + Int.ofNat dj1) (2 * Int.ofNat dj1)

/-- Single-column size reduction update for row `k` against row `j`. -/
def sizeReduceColumn (s : LLLState n m) (j k : Fin n) (hjk : j.val < k.val) :
    LLLState n m :=
  let νjk := (s.ν.get k).get j
  let dj1 := s.d.get ⟨j.val + 1, Nat.succ_lt_succ j.isLt⟩
  if hreduce : 2 * Int.natAbs νjk > dj1 then
    let r := nearestQuotient νjk dj1
    let b' := GramSchmidt.Int.sizeReduce s.b j k r
    let ν' : Matrix Int n n :=
      Matrix.ofFn fun i l =>
        if hik : i = k then
          if hlj : l.val < j.val then
            (s.ν.get i).get l - r * (s.ν.get j).get l
          else if hljEq : l = j then
            (s.ν.get i).get l - r * Int.ofNat dj1
          else
            (s.ν.get i).get l
        else
          (s.ν.get i).get l
    { b := b'
      ν := ν'
      d := s.d
      ν_eq := by
        intro i l hi hl hli
        sorry
      d_eq := by
        intro i hi
        sorry }
  else
    s

/-- Size-reduce row `k` against each earlier row using the stored integer
scaled coefficients. -/
def sizeReduce (s : LLLState n m) (k : Nat) : LLLState n m :=
  if hk : k < n then
    let kFin : Fin n := ⟨k, hk⟩
    ((List.finRange k).reverse).foldl
      (fun state j =>
        let jFin : Fin n := ⟨j.val, Nat.lt_trans j.isLt hk⟩
        LLLState.sizeReduceColumn state jFin kFin j.isLt)
      s
  else
    s

/-- Swap adjacent rows `k - 1` and `k`, updating the stored scaled coefficients
and Gram determinants with the integer formulas from the LLL specification. -/
def swapStep (s : LLLState n m) (k : Nat) : LLLState n m :=
  if hk : k < n then
    if hk0 : 0 < k then
      let kFin : Fin n := ⟨k, hk⟩
      let km1 : Fin n := GramSchmidt.prevRow kFin hk0
      let B := (s.ν.get kFin).get km1
      let dkPrev := s.d.get ⟨km1.val, Nat.lt_succ_of_lt km1.isLt⟩
      let dk := s.d.get ⟨k, Nat.lt_succ_of_lt hk⟩
      let dkNext := s.d.get ⟨k + 1, Nat.succ_lt_succ hk⟩
      let dk' : Nat :=
        Int.toNat (((Int.ofNat dkNext * Int.ofNat dkPrev + B ^ 2) / Int.ofNat dk))
      let b' := GramSchmidt.Int.adjacentSwap s.b kFin hk0
      let d' : Vector Nat (n + 1) :=
        Vector.ofFn fun i => if i.val = k then dk' else s.d.get i
      let ν' : Matrix Int n n :=
        Matrix.ofFn fun i j =>
          if hikm1 : i = km1 then
            if hjlt : j.val < km1.val then
              (s.ν.get kFin).get j
            else
              (s.ν.get i).get j
          else if hik : i = kFin then
            if hjEq : j = km1 then
              B
            else if hjlt : j.val < km1.val then
              (s.ν.get km1).get j
            else
              (s.ν.get i).get j
          else if hklt : k < i.val then
            if hjEq : j = km1 then
              (((s.ν.get i).get km1 * Int.ofNat dk') + ((s.ν.get i).get kFin * B)) /
                Int.ofNat dk
            else if hjEq' : j = kFin then
              (((s.ν.get i).get kFin * Int.ofNat dkPrev) - ((s.ν.get i).get km1 * B)) /
                Int.ofNat dk
            else
              (s.ν.get i).get j
          else
            (s.ν.get i).get j
      { b := b'
        ν := ν'
        d := d'
        ν_eq := by
          intro i j hi hj hij
          sorry
        d_eq := by
          intro i hi
          sorry }
    else
      s
  else
    s

/-- Size reduction leaves the stored Gram determinants unchanged. -/
theorem sizeReduce_d (s : LLLState n m) (k : Nat) :
    (s.sizeReduce k).d = s.d := by
  sorry

/-- Size reduction preserves the Gram-Schmidt basis of the state basis matrix. -/
theorem sizeReduce_basis (s : LLLState n m) (k : Nat) :
    GramSchmidt.Int.basis (s.sizeReduce k).b = GramSchmidt.Int.basis s.b := by
  sorry

/-- Adjacent swaps preserve the generated lattice. -/
theorem swapStep_memLattice_iff (s : LLLState n m) (k : Nat) (v : Vector Int m) :
    Matrix.memLattice (s.swapStep k).b v ↔ Matrix.memLattice s.b v := by
  sorry

/-- The updated swap state still packages the intended scaled coefficient
representation for its basis. -/
theorem swapStep_ν_eq
    (s : LLLState n m) (k : Nat)
    (i j : Nat) (hi : i < n) (hj : j < n) (hji : j < i) :
    (((s.swapStep k).ν.get ⟨i, hi⟩).get ⟨j, hj⟩ : Rat) =
      (((s.swapStep k).d.get ⟨j + 1, Nat.succ_lt_succ hj⟩ : Nat) : Rat) *
        (((GramSchmidt.Int.coeffs (s.swapStep k).b).get ⟨i, hi⟩).get ⟨j, hj⟩) := by
  simpa using (s.swapStep k).ν_eq i j hi hj hji

/-- The updated swap state still packages the intended Gram-determinant
representation for its basis. -/
theorem swapStep_d_eq (s : LLLState n m) (k i : Nat) (hi : i < n + 1) :
    (s.swapStep k).d.get ⟨i, hi⟩ =
      GramSchmidt.Int.gramDet (s.swapStep k).b i (Nat.le_of_lt_succ hi) := by
  simpa using (s.swapStep k).d_eq i hi

/-- Recover a single rational Gram-Schmidt coefficient from the integer state.
This exists for the proof layer; later executable code continues to work over
the stored integer data. -/
noncomputable def gramSchmidtCoeff (s : LLLState n m) (i j : Nat)
    (hi : i < n) (hj : j < n) : Rat :=
  (((s.ν.get ⟨i, hi⟩).get ⟨j, hj⟩ : Int) : Rat) / (s.d.get ⟨j + 1, Nat.succ_lt_succ hj⟩ : Rat)

/-- The multiplicative potential used by the LLL termination argument:
`d₁ * ... * dₙ`. -/
def potential (s : LLLState n m) : Nat :=
  (List.finRange n).foldl
    (fun acc i => acc * s.d.get ⟨i.val + 1, Nat.succ_lt_succ i.isLt⟩)
    1

end LLLState

end Hex
