import HexGramSchmidt

/-!
Core `HexLll` scaffolding.

This module introduces the first `HexLll` API slice promised by the
specification: integer-lattice membership for row spans together with
the positivity-based independence predicate that later LLL state and
algorithm code use to assume nondegenerate Gram-Schmidt data.
-/

namespace HexMatrix
namespace Matrix

/-- A vector lies in the integer lattice generated by the rows of `b`. -/
def memLattice (b : Matrix Int n m) (v : Vector Int m) : Prop :=
  ∃ c : Vector Int n, b * c = v

/--
The rows of `b` are independent when every nonempty leading Gram
determinant is positive.
-/
def independent (b : Matrix Int n m) : Prop :=
  ∀ k : Fin n, 0 < Hex.GramSchmidt.Int.gramDet b (k.1 + 1) (Nat.succ_le_of_lt k.2)

end Matrix
end HexMatrix
