name = "Hex"
version = "0.1.0"
defaultTargets = ["HexManual"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0-rc2"

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso.git"
rev = "v4.30.0-rc2"

[[lean_lib]]
name = "HexArith"

[[lean_lib]]
name = "HexPoly"

[[lean_lib]]
name = "HexMatrix"

[[lean_lib]]
name = "HexModArith"

[[lean_lib]]
name = "HexGramSchmidt"

[[lean_lib]]
name = "HexGF2"

[[lean_lib]]
name = "HexPolyZ"

[[lean_lib]]
name = "HexLLL"

[[lean_lib]]
name = "HexPolyFp"

[[lean_lib]]
name = "HexGfqRing"

[[lean_lib]]
name = "HexGfqField"

[[lean_lib]]
name = "HexBerlekamp"

[[lean_lib]]
name = "HexHensel"

[[lean_lib]]
name = "HexConway"

[[lean_lib]]
name = "HexGfq"

[[lean_lib]]
name = "HexBerlekampZassenhaus"

[[lean_lib]]
name = "HexPolyMathlib"
needs = ["@mathlib"]

[[lean_lib]]
name = "HexMatrixMathlib"
needs = ["@mathlib"]

[[lean_lib]]
name = "HexModArithMathlib"
needs = ["@mathlib"]

[[lean_lib]]
name = "HexGramSchmidtMathlib"
needs = ["@mathlib"]

[[lean_lib]]
name = "HexPolyZMathlib"
needs = ["@mathlib"]

[[lean_lib]]
name = "HexLLLMathlib"
needs = ["@mathlib"]

[[lean_lib]]
name = "HexBerlekampMathlib"
needs = ["@mathlib"]

[[lean_lib]]
name = "HexHenselMathlib"
needs = ["@mathlib"]

[[lean_lib]]
name = "HexGF2Mathlib"
needs = ["@mathlib"]

[[lean_lib]]
name = "HexGfqMathlib"
needs = ["@mathlib"]

[[lean_lib]]
name = "HexBerlekampZassenhausMathlib"
needs = ["@mathlib"]

[[lean_lib]]
name = "HexManual"
needs = [
  "@verso",
  "HexArith",
  "HexPoly",
  "HexMatrix",
  "HexModArith",
  "HexGramSchmidt",
  "HexGF2",
  "HexPolyZ",
  "HexLLL",
  "HexPolyFp",
  "HexGfqRing",
  "HexGfqField",
  "HexBerlekamp",
  "HexHensel",
  "HexConway",
  "HexGfq",
  "HexBerlekampZassenhaus",
  "HexPolyMathlib",
  "HexMatrixMathlib",
  "HexModArithMathlib",
  "HexGramSchmidtMathlib",
  "HexPolyZMathlib",
  "HexLLLMathlib",
  "HexBerlekampMathlib",
  "HexHenselMathlib",
  "HexGF2Mathlib",
  "HexGfqMathlib",
  "HexBerlekampZassenhausMathlib",
]
