import HexLLL.Basic
import HexMatrixMathlib.RankSpanNullspace

/-!
Mathlib bridge lemmas for the lattice surface of `hex-lll`.

This module packages the integer row lattice generated by an executable
`Hex.Matrix` as a Mathlib `Submodule ℤ`, then relates membership in that
submodule to the executable `Hex.Matrix.memLattice` predicate used by
`HexLLL`.
-/

namespace HexLLLMathlib

/-- The Mathlib `Submodule ℤ` generated by the rows of an executable integer
matrix. -/
def latticeSubmodule (b : Hex.Matrix Int n m) : Submodule ℤ (Fin m → ℤ) :=
  Submodule.span ℤ (Set.range fun i : Fin n => HexMatrixMathlib.vectorEquiv (Hex.Matrix.row b i))

theorem mem_latticeSubmodule_iff (b : Hex.Matrix Int n m) (v : Vector Int m) :
    HexMatrixMathlib.vectorEquiv v ∈ latticeSubmodule b ↔ Hex.Matrix.memLattice b v := by
  let E := (Hex.Matrix.rref_isRREF b).toIsEchelonForm
  have hSpan :
      E.spanContains v = true ↔
        HexMatrixMathlib.vectorEquiv v ∈ latticeSubmodule b := by
    simpa [latticeSubmodule, HexMatrixMathlib.matrixEquiv_row] using
      (HexMatrixMathlib.spanContains_iff_mem_span (E := E) v)
  have hExec : E.spanContains v = true ↔ Hex.Matrix.memLattice b v := by
    simpa [Hex.Matrix.memLattice] using (E.spanContains_iff v)
  exact hSpan.symm.trans hExec

theorem memLattice_iff_mem_latticeSubmodule (b : Hex.Matrix Int n m) (v : Vector Int m) :
    Hex.Matrix.memLattice b v ↔ HexMatrixMathlib.vectorEquiv v ∈ latticeSubmodule b :=
  (mem_latticeSubmodule_iff b v).symm

theorem row_mem_latticeSubmodule (b : Hex.Matrix Int n m) (i : Fin n) :
    HexMatrixMathlib.vectorEquiv (Hex.Matrix.row b i) ∈ latticeSubmodule b := by
  exact Submodule.subset_span (Set.mem_range_self i)

end HexLLLMathlib
