import HexLLL.Basic
import HexMatrixMathlib.RankSpanNullspace

/-!
Mathlib bridge lemmas for the lattice surface of `hex-lll`.

This module packages the integer row lattice generated by an executable
`Hex.Matrix` as a Mathlib `Submodule ℤ`, then relates membership in that
submodule to the executable `Hex.Matrix.memLattice` predicate used by
`HexLLL`.
-/

namespace HexLLLMathlib

/-- The Mathlib `Submodule ℤ` generated by the rows of an executable integer
matrix. -/
def latticeSubmodule (b : Hex.Matrix Int n m) : Submodule ℤ (Fin m → ℤ) :=
  Submodule.span ℤ (Set.range fun i : Fin n => HexMatrixMathlib.vectorEquiv (Hex.Matrix.row b i))

theorem mem_latticeSubmodule_iff (b : Hex.Matrix Int n m) (v : Vector Int m) :
    HexMatrixMathlib.vectorEquiv v ∈ latticeSubmodule b ↔ Hex.Matrix.memLattice b v := by
  sorry

theorem memLattice_iff_mem_latticeSubmodule (b : Hex.Matrix Int n m) (v : Vector Int m) :
    Hex.Matrix.memLattice b v ↔ HexMatrixMathlib.vectorEquiv v ∈ latticeSubmodule b :=
  (mem_latticeSubmodule_iff b v).symm

theorem row_mem_latticeSubmodule (b : Hex.Matrix Int n m) (i : Fin n) :
    HexMatrixMathlib.vectorEquiv (Hex.Matrix.row b i) ∈ latticeSubmodule b := by
  exact Submodule.subset_span (Set.mem_range_self i)

/-- View a Mathlib-side integer lattice vector as a finite function for
Mathlib's norm API. -/
noncomputable def intVectorFn (x : Fin m → ℤ) : Fin m → ℤ :=
  x

/-- View an executable rational row as a finite function for Mathlib's
norm API. -/
noncomputable def ratRowFn (row : Vector Rat m) : Fin m → ℚ :=
  fun j : Fin m => row[j]

/-- Mathlib-norm formulation of the executable short-vector lower bound.

The input vector is assumed to lie in the Mathlib `latticeSubmodule`; the
proof route converts that hypothesis back through `mem_latticeSubmodule_iff`
before applying the executable squared-norm theorem. -/
theorem exists_gramSchmidt_norm_le_of_mem_latticeSubmodule
    [Norm (Fin m → ℚ)] [Norm (Fin m → ℤ)]
    (b : Hex.Matrix Int n m) (hli : Hex.Matrix.independent b)
    (x : Fin m → ℤ) (hx : x ∈ latticeSubmodule b) (hx0 : x ≠ 0) :
    ∃ i : Fin n,
      ‖ratRowFn ((Hex.GramSchmidt.Int.basis b).row i)‖ ≤
        ‖intVectorFn x‖ := by
  let v : Vector Int m := HexMatrixMathlib.vectorEquiv.symm x
  have hxExec : Hex.Matrix.memLattice b v := by
    have hx' : HexMatrixMathlib.vectorEquiv v ∈ latticeSubmodule b := by
      simpa [v] using hx
    exact (mem_latticeSubmodule_iff b v).mp hx'
  have _ := Hex.Matrix.normSq_latticeVec_ge_min_basis_normSq b hli v hxExec (by
    sorry)
  sorry

end HexLLLMathlib
