import Mathlib.LinearAlgebra.Span.Defs
import HexMatrix.Span
import HexMatrixMathlib.MatrixEquiv

/-!
Bridge scaffolding between Hex's executable row-span membership API and
Mathlib's row-span submodule for dense matrices.

This module states the Phase 1 correspondence layer identifying Hex's
row-span witnesses and boolean span-membership test with membership in the
submodule spanned by the rows of the transported Mathlib matrix.
-/

namespace HexMatrixMathlib

universe u

variable {R : Type u} [Semiring R] {n m : Nat}

/--
The Mathlib row-span submodule generated by the rows of `M` after transport
along `matrixEquiv`.
-/
def rowSpan (M : HexMatrix.Matrix R n m) : Submodule R (Fin m → R) :=
  Submodule.span R (Set.range fun i : Fin n => matrixEquiv R n m M i)

/--
Any explicit Hex row-span witness produced by `spanCoeffs` maps into Mathlib's
row-span submodule.
-/
theorem mem_rowSpan_of_spanCoeffs_eq_some
    (M : HexMatrix.Matrix R n m)
    (D : HexMatrix.RowEchelonData R n m)
    (E : HexMatrix.IsEchelonForm M D)
    (v : Vector R m) (c : Vector R n) :
    E.spanCoeffs v = some c →
      vectorEquiv R m v ∈ rowSpan (R := R) M := by
  sorry

/--
Hex's boolean row-span test agrees with membership in the Mathlib row-span
submodule generated by the rows of `M`.
-/
theorem spanContains_iff_mem_rowSpan
    (M : HexMatrix.Matrix R n m)
    (D : HexMatrix.RowEchelonData R n m)
    (E : HexMatrix.IsEchelonForm M D)
    (v : Vector R m) :
    E.spanContains v = true ↔
      vectorEquiv R m v ∈ rowSpan (R := R) M := by
  sorry

end HexMatrixMathlib
