#!/usr/bin/env python3
"""One-shot generator for the committed Lübeck Conway-polynomial cache.

Downloads Frank Lübeck's flat-file Conway-polynomial database
(``CPimport.txt``), filters it to the coverage subset used by the
``hex-conway`` oracle, and writes the result as JSON to
``scripts/oracle/conway_lubeck.json``.

The generated file is committed to the repository.  CI does **not**
invoke this script — the cache is treated as an immutable third source
of truth, regenerated by hand only when the coverage range needs to
grow.

Schema of the output JSON:

    { "<p>,<n>": [c0, c1, ..., cn] }

with coefficients constant-first (so ``c0`` is the constant term and
the leading ``cn`` is ``1`` because Conway polynomials are monic).

Usage::

    python3 scripts/oracle/conway_lubeck_cache.py             # default
    python3 scripts/oracle/conway_lubeck_cache.py --source FILE
    python3 scripts/oracle/conway_lubeck_cache.py --output PATH

Stdlib only.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.request
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "scripts" / "oracle" / "conway_lubeck.json"
LUBECK_URL = (
    "http://www.math.rwth-aachen.de/~Frank.Luebeck/data/ConwayPol/CPimport.txt"
)

# Coverage matches HexConway/EmitFixtures.lean and the deliverable
# scope of issue #1997.  Keep these two in sync when extending.
COVERAGE_PRIMES = (2, 3, 5, 7, 11, 13)
COVERAGE_NMAX = 6

ENTRY_RE = re.compile(r"^\[(\d+),(\d+),\[([0-9,\-]+)\]\],?$")


def fetch(source: str) -> str:
    """Read CPimport.txt from a URL or local path."""
    if source.startswith(("http://", "https://")):
        with urllib.request.urlopen(source, timeout=60) as fh:
            return fh.read().decode("utf-8", errors="replace")
    return Path(source).read_text(encoding="utf-8", errors="replace")


def parse(text: str, primes: tuple[int, ...], n_max: int) -> dict[str, list[int]]:
    out: dict[str, list[int]] = {}
    primes_set = set(primes)
    for raw in text.splitlines():
        line = raw.strip()
        m = ENTRY_RE.match(line)
        if not m:
            continue
        p = int(m.group(1))
        n = int(m.group(2))
        if p not in primes_set or not (1 <= n <= n_max):
            continue
        coeffs = [int(c) for c in m.group(3).split(",")]
        out[f"{p},{n}"] = coeffs
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        default=LUBECK_URL,
        help="URL or local path to CPimport.txt (default: upstream Lübeck URL)",
    )
    parser.add_argument(
        "--output",
        default=str(DEFAULT_OUTPUT),
        help=f"output JSON path (default: {DEFAULT_OUTPUT.relative_to(REPO_ROOT)})",
    )
    args = parser.parse_args(argv)

    text = fetch(args.source)
    entries = parse(text, COVERAGE_PRIMES, COVERAGE_NMAX)
    if not entries:
        print(
            f"error: no entries parsed from {args.source!r} "
            f"(coverage primes={COVERAGE_PRIMES}, n_max={COVERAGE_NMAX})",
            file=sys.stderr,
        )
        return 1
    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        json.dumps(entries, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(
        f"wrote {len(entries)} Conway entries to "
        f"{out_path.relative_to(REPO_ROOT)}",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
