#!/usr/bin/env python3
"""PARI (via cypari2) + Lübeck-cache oracle driver for `hex-conway`.

Reads a JSONL stream produced by `lake exe hexconway_emit_fixtures`
(or the committed sample at
`conformance-fixtures/HexConway/conway.jsonl`) and re-checks each
`(p, n)` Conway-polynomial lookup against two independent sources:

* **PARI** via cypari2: `pari.ffinit(p, n)` returns the Conway
  polynomial when the entry is in PARI's database.  Modern PARI
  ships the same upstream Lübeck data, so we treat this as one
  external check.
* **Lübeck flat-file cache**: `scripts/oracle/conway_lubeck.json`,
  generated by `scripts/oracle/conway_lubeck_cache.py` from
  `CPimport.txt`.  This is parsed independently of PARI, providing
  genuine third-source coverage even where PARI's compiled-in
  database is missing or differs.

For every Lean result record:

* PARI ≡ Lübeck cache is asserted always (these must agree).
* Lean ≡ Lübeck cache is asserted only when Lean returned a
  committed entry (`value` ≠ `null`).  Entries Lean has not yet
  committed still get the PARI ≡ Lübeck cross-check, so the cache
  itself is being continuously validated against PARI in CI.

On mismatch, writes a JSON failure record under
`conformance-failures/` and exits non-zero so CI fails the job.

Usage::

    # CI: pipe Lean's emission directly into the oracle.
    lake exe hexconway_emit_fixtures | python3 scripts/oracle/conway_pari.py

    # Local: replay against the committed sample.
    python3 scripts/oracle/conway_pari.py --check

    # Read from an explicit JSONL path.
    python3 scripts/oracle/conway_pari.py path/to/file.jsonl
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parent.parent.parent
DEFAULT_FIXTURE = REPO_ROOT / "conformance-fixtures" / "HexConway" / "conway.jsonl"
DEFAULT_CACHE = REPO_ROOT / "scripts" / "oracle" / "conway_lubeck.json"
DEFAULT_FAILURE_DIR = REPO_ROOT / "conformance-failures"

# Allow `import scripts.oracle.common` even when invoked as a script.
sys.path.insert(0, str(REPO_ROOT))

from scripts.oracle.common import (  # noqa: E402
    OracleMismatch,
    assert_equal,
    read_fixtures,
    split_fixtures_results,
)


def _trim_zeros(coeffs) -> list[int]:
    out = [int(c) for c in coeffs]
    while out and out[-1] == 0:
        out.pop()
    return out


def _pari_conway(pari, p: int, n: int) -> list[int]:
    """Run PARI's `ffinit(p, n)` and return the polynomial coefficients
    as constant-first nonnegative integers in ``[0, p)``.

    `ffinit` returns a polynomial in some variable; `Vecrev` extracts
    the coefficients constant-first; `Mod`/lift normalises into
    ``[0, p)``.  The leading coefficient is always ``1`` for `ffinit`
    output (it returns monic irreducible polynomials).
    """
    poly = pari.ffinit(p, n)
    raw = [int(c) for c in pari.Vecrev(poly)]
    return _trim_zeros([c % p for c in raw])


def _pari_version(pari) -> str:
    try:
        v = pari("Str(version())")
        return str(v)
    except Exception:
        return "unknown"


def _load_cache(path: Path) -> dict[tuple[int, int], list[int]]:
    raw = json.loads(path.read_text(encoding="utf-8"))
    out: dict[tuple[int, int], list[int]] = {}
    for key, value in raw.items():
        p_str, n_str = key.split(",", 1)
        out[(int(p_str), int(n_str))] = [int(c) for c in value]
    return out


def check(
    source: str | Path | None,
    *,
    cache_path: Path,
    failure_dir: Path,
    profile: str,
    seed: int,
) -> int:
    import cypari2  # type: ignore[import-not-found]
    pari = cypari2.Pari()
    cache = _load_cache(cache_path)
    cases, results = split_fixtures_results(read_fixtures(source))
    oracle_version = _pari_version(pari)
    failures = 0
    checked = 0
    for result in results:
        lib = result["lib"]
        case_id = result["case"]
        op = result["op"]
        lean_value = result["value"]
        try:
            if op == "conway_lookup":
                pn = cases[(lib, f"{case_id}/pn")]
                if pn["kind"] != "prime":
                    raise OracleMismatch(
                        f"{lib}/{case_id}: expected prime fixture for /pn, "
                        f"got kind {pn['kind']!r}"
                    )
                p = int(pn["p"])
                n = int(pn["n"])
                cache_value = cache.get((p, n))
                if cache_value is None:
                    raise OracleMismatch(
                        f"{lib}/{case_id}: (p={p}, n={n}) absent from "
                        f"Lübeck cache {cache_path}"
                    )
                pari_value = _pari_conway(pari, p, n)
                input_record = {"p": p, "n": n}
                # PARI ≡ Lübeck cache: required for every fixture.
                assert_equal(
                    cache_value,
                    pari_value,
                    library=lib,
                    case_id=f"{case_id}:pari_vs_lubeck",
                    kind="conway_lookup",
                    input_record=input_record,
                    oracle_name="cypari2/PARI vs. Lübeck cache",
                    oracle_version=oracle_version,
                    failure_dir=failure_dir,
                    profile=profile,
                    seed=seed,
                )
                checked += 1
                # Lean ≡ Lübeck cache: only required where Lean has
                # committed an entry (lookup returned `some`).
                if lean_value is not None:
                    lean_coeffs = [int(c) for c in lean_value]
                    assert_equal(
                        cache_value,
                        lean_coeffs,
                        library=lib,
                        case_id=f"{case_id}:lean_vs_lubeck",
                        kind="conway_lookup",
                        input_record=input_record,
                        oracle_name="Lean vs. Lübeck cache",
                        oracle_version=oracle_version,
                        failure_dir=failure_dir,
                        profile=profile,
                        seed=seed,
                    )
                    checked += 1
            else:
                raise OracleMismatch(
                    f"{lib}/{case_id}: unsupported op {op!r} "
                    f"in conway_pari.py; extend the driver."
                )
        except OracleMismatch as exc:
            failures += 1
            print(f"FAIL {lib}/{case_id} ({op}): {exc}", file=sys.stderr)
    print(
        f"conway_pari.py: checked {checked} comparison(s), "
        f"{failures} failure(s)",
        file=sys.stderr,
    )
    return 1 if failures else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    src = parser.add_mutually_exclusive_group()
    src.add_argument(
        "input",
        nargs="?",
        help="JSONL fixture path (default: stdin)",
    )
    src.add_argument(
        "--check",
        action="store_true",
        help=f"read the committed sample at {DEFAULT_FIXTURE.relative_to(REPO_ROOT)}",
    )
    parser.add_argument(
        "--cache",
        default=str(DEFAULT_CACHE),
        help=f"Lübeck cache JSON (default: {DEFAULT_CACHE.relative_to(REPO_ROOT)})",
    )
    parser.add_argument(
        "--failure-dir",
        default=os.environ.get("HEX_FAILURE_DIR", str(DEFAULT_FAILURE_DIR)),
        help="directory for JSON failure records",
    )
    parser.add_argument("--profile", default="ci")
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args(argv)

    if args.check:
        source: str | None = str(DEFAULT_FIXTURE)
    else:
        source = args.input  # may be None → stdin

    try:
        import cypari2  # noqa: F401
    except ImportError:
        # Mirror the SPEC's `if_available` mode: a missing oracle is a
        # skip, not a failure.  CI installs cypari2 (which itself needs
        # `libpari-dev`) before this script runs; a failure here in CI
        # means install failed.
        print("SKIP: cypari2 not installed", file=sys.stderr)
        return 0

    return check(
        source,
        cache_path=Path(args.cache),
        failure_dir=Path(args.failure_dir),
        profile=args.profile,
        seed=args.seed,
    )


if __name__ == "__main__":
    raise SystemExit(main())
